[tool.poetry]
name = "cc-core"
version = "6.1.0"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/cc-core"
homepage = "https://www.curious-containers.cc/"
description = "CC-Core is part of the Curious Containers project. It provides common functionality for other parts of Curious Containers and implements agents to run data-driven experiments defined in RED or CWL format."

[tool.poetry.dependencies]
python = "^3.4"
requests = "^2.18"
jsonschema = "^2.6"
psutil = "^5.4"
"ruamel.yaml" = "^0.15"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ccagent = 'cc_core.agent.main:main'
